disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "My Portfolio"

# [menu]

#   [[menu.main]]
#     name  = "Home"
#     pageRef = "/"
#     weight = 10

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"
