baseURL = 'https://fiwon123.github.io/'
languageCode = 'en-us'
title = 'Felipe Inoue'
theme = "PaperMod"

[params]
    # Define the color scheme (white, blue, black variations)
    defaultTheme = "auto"
    ShowReadingTime = true
    ShowShareButtons = false
    ShowPostNavLinks = true
    ShowCodeCopyButtons = true
    ShowBreadCrumbs = false
    ShowWordCount = false
    ShowToc = true
    ShowFooter = true
    disableScrollToTop = false
    DateFormat = "Jan 2, 2006"


    author = "Felipe Inoue"
    description = "Tooling Developer · Automation · Developer Experience"
    favicon = "favicon.ico"
    hideFooter = false
    hideCopyright = false

[menu]

    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 1

    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects/"
        weight = 2

    [[menu.main]]
        identifier = "experience"
        name = "Experience"
        url = "/experience/"
        weight = 3